# Problem

# The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,... are generated by the following simple rule Fn = Fn - 1 + Fn - 2.

# Given:
# A positive integer n <= 25.

# Return:
# The value of Fn.

n = File.read('fibo.txt').to_i

def fib n
  return n if n < 2

  fib(n - 1) + fib(n - 2)
end

puts fib 25
